import React from 'react';
import { Sparkles, ArrowUpRight } from 'lucide-react';

const Footer = () => {
  return (
    <footer className="app-footer">
      <div className="footer-top">
        <div className="footer-brand-section">
          <div className="footer-brand">
            <Sparkles size={16} className="footer-brand-icon" />
            <span className="footer-brand-title">CARLEASE AI</span>
            <span className="footer-brand-version">// SYS_VER.1.0.4</span>
          </div>
          <p className="footer-disclaimer">
            ADVISORY NOTICE: ALL INTEREST RATE CALCULATIONS, FEE AUDITS, AND NEGOTIATION SCRIPTS ARE GENERATED BY LARGE LANGUAGE MODELS FOR INFORMATIONAL PURPOSES ONLY. ALWAYS VERIFY FINANCIAL MATH WITH A CERTIFIED PROFESSIONAL BEFORE SIGNING.
          </p>
        </div>

        <div className="footer-links-grid">
          <div className="footer-links-col">
            <span className="footer-col-title">INTEGRATIONS</span>
            <a href="https://www.nhtsa.gov/" target="_blank" rel="noopener noreferrer" className="footer-link">
              NHTSA API <ArrowUpRight size={10} />
            </a>
            <a href="https://vpic.nhtsa.dot.gov/api/" target="_blank" rel="noopener noreferrer" className="footer-link">
              VPIC ENGINE <ArrowUpRight size={10} />
            </a>
            <a href="#" className="footer-link">
              LEASING CALCULATOR
            </a>
          </div>

          <div className="footer-links-col">
            <span className="footer-col-title">DOCUMENTATION</span>
            <a href="#" className="footer-link">USER MANUAL</a>
            <a href="#" className="footer-link">AUDIT CRITERIA</a>
            <a href="#" className="footer-link">NEGOTIATION STRATEGY</a>
          </div>

          <div className="footer-links-col">
            <span className="footer-col-title">SYSTEM STATUS</span>
            <div className="status-indicator">
              <span className="status-dot"></span>
              <span className="status-text">CORE SERVICE: ONLINE</span>
            </div>
            <div className="status-detail">ENG: GEMINI 1.5 FLASH</div>
            <div className="status-detail">LATENCY: &lt;140ms</div>
          </div>
        </div>
      </div>

      <div className="footer-bottom">
        <span className="footer-copyright">
          © {new Date().getFullYear()} CARLEASE AI. STARK ARCHITECT SYSTEM. ALL RIGHTS RESERVED.
        </span>
        <span className="footer-design-tag">
          DESIGNED FOR AUTOMOTIVE INTELLIGENCE
        </span>
      </div>
    </footer>
  );
};

export default Footer;
